language: go

go:
- tip

# Don't email me the results of the test runs.
notifications:
  email: false

before_script:
- go get -u golang.org/x/lint/golint

script:
- go test -v -race ./...
- go run main.go
- go vet ./...
- golint -set_exit_status $(go list ./...)
