language: go

go:
- 1.9
- master

# Don't email me the results of the test runs.
notifications:
  email: false

before_install:
- sudo apt-get -qq update
- sudo apt-get install -y golang-glide

before_script:
- go get github.com/golang/lint/golint
- go get honnef.co/go/tools/cmd/megacheck
- glide up

script:
- go run main.go
- go vet ./...
- megacheck ./...
- golint -set_exit_status $(go list ./...)
