language: go

go:
- "1.10"

# Don't email me the results of the test runs.
notifications:
  email: false

before_install:
- go get -v github.com/Masterminds/glide
- cd $GOPATH/src/github.com/Masterminds/glide
- git checkout v0.13.1
- go install && cd -
- glide install

before_script:
- go get github.com/golang/lint/golint
- go get honnef.co/go/tools/cmd/megacheck
- glide up

script:
- go run main.go
- go vet ./...
- megacheck ./...
- golint -set_exit_status $(go list ./...)
